routes/web.php
    Route::get('solicitud-aprobar-rendicion', array('uses' => 'SolicitudController@aprobarRendicionSolicitud'));

    Route::get('solicitud-aprobacion-creada', array('uses' => 'SolicitudController@guardarAprobacionCreada'));
    Route::get('solicitud-aprobacion-autorizada', array('uses' => 'SolicitudController@guardarAprobacionAutorizada'));
    Route::get('solicitud-aprobacion-pendiente', array('uses' => 'SolicitudController@guardarAprobacionPendiente'));
    Route::get('solicitud-aprobacion-pendiente2', array('uses' => 'SolicitudController@guardarAprobacionPendiente2'));
    Route::get('solicitud-aprobacion-pendiente3', array('uses' => 'SolicitudController@guardarAprobacionPendiente3'));
    Route::get('solicitud-aprobacion-pendiente4', array('uses' => 'SolicitudController@guardarAprobacionPendiente4'));
    Route::get('solicitud-aprobacion-pendiente5', array('uses' => 'SolicitudController@guardarAprobacionPendiente5'));

    Route::get('solicitud-aprobacion-transferencia', array('uses' => 'SolicitudController@guardarAprobacionTransferencia'));

    Route::post('solicitud-rechazo', array('uses' => 'SolicitudController@rechazo'));
    Route::post('solicitud-observacion', array('uses' => 'SolicitudController@observacion'));

    Route::post('solicitud-tesoreria', 'SolicitudController@buscadorTesoreria');
    Route::get('solicitud-tesoreria', 'SolicitudController@tesoreria')
        ->name('solicitudes-tesoreria');
    Route::get('registro-tesoreria/{solicitud_id}', 'SolicitudController@registroTesoreria');

    Route::post('aprobador-rendiciones', 'SolicitudController@aprobadorRendicion');
    Route::get('aprobador-rendiciones', 'SolicitudController@aprobadorRendicion');

    //Aprobador parcial
    Route::get('aprobador/solicitudes/parciales', 'SolicitudController@aprParcialSolicitudes');

    //Pdf
    Route::post('/download-pdf', 'PdfController@generar');
    Route::get('solicitud-imprimir', 'PdfController@imprimirSolicitud')->name('solicitud-imprimir');
    Route::get('solicitud-imprimir/completa', 'PdfController@imprimirSolicitudCompleta')->name('solicitud-imprimir.completa');

    Route::get('solicitud-imprimir/rendicion', 'PdfController@imprimirRendicionSolicitud')->name('solicitud-imprimir.rendicion');

    Route::get('solicitud-imprimir/formulario/af', 'PdfController@imprimirFormularioAF')->name('solicitud-imprimir.formulario.af');
    Route::get('solicitud-imprimir/formulario/items-af', 'PdfController@imprimirFormularioItemsAF')->name('solicitud-imprimir.formulario.itemsaf');

    Route::get('solicitud-imprimir-transferencia', 'PdfController@imprimirSolicitudTransferencia')->name('solicitud-imprimir.transferencia');

    //Proyectos
    Route::resource('proyectos', 'ProyectosController');
    Route::post('/proyectos-form', function(){
        return view('proyectos.form');
    })->name('proyectos-form');

    Route::post('solicitud-guardar-archivo', array('uses' => 'SolicitudController@guardarArchivo'));

    //EmpresaUsuario
    Route::post('/asignar-empresa', 'UsuarioController@UsuarioEmpresa')->name('asignar-empresa');
    Route::post('/guardar-asignacion-empresa', 'UsuarioController@UsuarioEmpresaStore')->name('guardar-asignacion-empresa');

    //Estados
    Route::resource('estados', 'EstadosController');

    //Roles
    Route::resource('roles', 'RolesController');

    //Bancos
    Route::resource('bancos', 'BancosController');

    //Cuentas
    Route::resource('cuentas', 'BancoCuentasController');

    //******* JSON *******
    Route::get('json/tipo_cambio', 'JsonController@getCambio');
    Route::get('json/usuario_proyectos/{usuario_id}', 'JsonController@getUsuarioProyectos');
    Route::get('json/documentos_solicitud/{solicitud_id}', 'JsonController@getDocumentosSolicitud');
    Route::get('json/documentos_rendicion/{solicitud_id}', 'JsonController@getDocumentosRendicion')
        ->name('json.documentos_rendicion');
    Route::get('json/items_solicitud/{solicitud_id}', 'JsonController@getItemsSolicitud');
    Route::get('json/items_tiene_antiguos/{solicitud_id}', 'JsonController@getCantidadItemsAntiguosSolicitud');
    Route::get('json/items_antiguos_solicitud/{solicitud_id}', 'JsonController@getItemsAntiguosSolicitud');
    Route::get('json/items_rendidos/{solicitud_id}', 'JsonController@getItemsRendidosSolicitud');
    Route::get('json/datos_solicitud/{solicitud_id}', 'JsonController@getDatosSolicitud');
    Route::get('json/asignacion_autorizador/{autorizador_id}', 'JsonController@getDatosAutorizadorAsignacion');
    Route::get('json/datos_item/{item_id}', 'JsonController@getDatosItem');
    Route::get('json/cantidad/estados/{empresa_id}', 'JsonController@getCantidadEstados');
    Route::get('json/cantidad/empresas/estados', 'JsonController@getCantidadEstadosEmpresas');
    Route::get('json/estados/solicitud', 'JsonController@getEstadosSolicitud');
    Route::get('json/porcentaje/aprobador/{aprobador_id}/{solicitud_id}', 'JsonController@getPorcentajeAprobador');
    Route::get('json/datos/cheque/{cheque_id}', 'JsonController@getDatosCheque');
    Route::get('json/proyectos/empresa/{empresa_id}', 'JsonController@getProyectosEmpresa');
    Route::get('json/datos/solicitud/{solicitud_id}', 'JsonController@getDocumentosSolicitud');
    Route::get('json/verifica/solicitud/completa/{solicitud_id}', 'JsonController@solicitudCompleta');
    Route::get('json/cuentas/empresa/{empresa_id}/{banco_id}', 'JsonController@getCuentasEmpresa');
    Route::get('json/bancos/empresa/{empresa_id}', 'JsonController@getBancosEmpresa');
    Route::get('json/tipos/compra', 'JsonController@getTiposCompra');
    Route::get('json/empresas', 'JsonController@getEmpresas');   
    Route::get('json/existe_proyecto/{usuario_id}/{proyecto_id}', 'JsonController@existeProyecto');
    Route::get('json/proyectos_usuario/{proyecto_id}/{usuario_id}', 'JsonController@proyectosUsuario');
    Route::get('json/item/rendicion/af/{solicitud_id}', 'JsonController@getDatosItemsAF');
    Route::get('json/item/formularios/af/{solicitud_id}', 'JsonController@getFormuItemsAF');
    Route::get('json/asignacion_aprorendicion/{usuario_id}', 'JsonController@getDatosAprorendicionAsignacion');
    Route::get('json/proyecto/fr/{proyecto_id}/', 'JsonController@getFrProyecto');

    //Password Generator
    Route::get('generador', 'JsonController@passGenerator');

    //Cheques
    Route::get('cheques/anulados', 'ChequesController@chequesAnulados')->name('cheques/anulados');
    Route::get('cheques/registrados', 'ChequesController@chequesRegistrados')->name('cheques/registrados');
    Route::resource('cheques', 'ChequesController');
    Route::post('cheque', 'ChequesController@index')->name('cheque');
    Route::get('cheque', 'ChequesController@index')->name('cheque');

    Route::get('cheque-lastEstado/{cheque_id}', 'ChequesController@getLastEstadoCheque')->name('cheque-lastEstado');
    Route::get('cheque/anular', array('uses' => 'ChequesController@anularCheque'));
    Route::get('cheque/anular/solicitud', array('uses' => 'ChequesController@anularSolicitudCheque'));

    //Configuraciones
    Route::resource('configuraciones', 'ConfiguracionesController');
    Route::get('configuracion/vidautil', 'ConfiguracionesController@solicitudDuracion')->name('configuracion/vidautil');

    //Rendiciones
    Route::get('rendiciones', 'SolicitudController@rendiciones')->name('rendiciones');
    Route::get('rendir/solicitud/{solicitud_id}', 'SolicitudController@rendir')->name('rendir/solicitud');
    Route::post('rendir/solicitud/item/', 'SolicitudController@itemRendicionStore')->name('rendir.solicitud.item');
    Route::post('rendir/solicitud/devolucion/', 'SolicitudController@itemDevolucionStore')->name('rendir.solicitud.devolucion');
    Route::post('finalizar/solicitud/', 'SolicitudController@finalizarSolicitudStore')->name('finalizar.solicitud');
    Route::get('solicitud-rendiciones', 'SolicitudController@solicitudRendiciones')->name('solicitud-rendiciones');
    Route::get('solicitud-aprobar-rendicion/{solicitud_id}', 'SolicitudController@solicitudAprobarRendicion')->name('solicitud-aprobar-rendicion');
    Route::post('solicitud-aprobar-rendicion-guardar/', array('uses' => 'SolicitudController@solicitudAprobarRendicionStore'))->name('solicitud.aprobar.rendicion.guardar');
    Route::post('solicitud-documentos/rendicion/guardar/', array('uses' => 'SolicitudController@solicitudDocumentoRendicionStore'))->name('solicitud.documentos.rendicion.guardar');

    //Servicios
    Route::get('servicios/empresas', 'ServiciosController@getEmpresas')->middleware('Bypass');

    //Documentos
    Route::get('/documentoshow/{id}',[
        'uses' => 'DocumentosController@getDocumentoShow',
        'as'=> 'documentos.showcr'
    ]);

    Route::get('json/documento/eliminar/{documento_id}', 'DocumentosController@eliminarDoc');

    Route::get('descargar/{id}', [
        'uses' => 'DocumentosController@getDocumento',
        'as'=> 'doc.descargar'
    ]);

    // ViewerJS
    Route::any('ViewerJS/{all?}', function(){
        return View::make('ViewerJS.index');
    });

    //Libreta Bancaria
    Route::get('libreta', 'LibretaBancariaController@index');
    Route::get('transferencia', 'LibretaBancariaController@transferencia')->name('transferencia');
    Route::post('transferencia/guardar', array('uses' => 'LibretaBancariaController@transferenciaStore'))->name('transferencia.store');
    Route::get('movimiento/ingreso', 'LibretaBancariaController@ingreso')->name('movimiento.ingreso');
    Route::post('movimiento/ingreso/guardar', array('uses' => 'LibretaBancariaController@ingresoStore'))->name('ingreso.store');
    Route::get('movimiento/egreso', 'LibretaBancariaController@egreso')->name('movimiento.egreso');

app/Bancos.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Bancos extends Model
{
    //Mutators
    public function setCodigoAttribute($value)
    {
        $this->attributes['codigo'] = mb_strtoupper($value);
    }

    public function setNombreAttribute($value)
    {
        $this->attributes['nombre'] = mb_strtoupper($value);
    }

    // One to Many ->
    public function cuentas(){
        return $this->hasMany('App\CuentaBancaria');
    }
}

app/Http/Controllers/BancosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\CuentaBancaria;
use App\Bancos;

use Session;

class BancosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $bancos = Bancos::all();
        return View('bancos.index')->withBancos($bancos);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('bancos.crear');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $banco = new Bancos;
        $banco->codigo    = mb_strtoupper(trim($request->codigo));
        $banco->nombre    = mb_strtoupper(trim($request->nombre));
        $banco->save();

        $bancos = Bancos::all();

        Session::flash('success', 'Banco Creado!!!');
        return redirect()->action('BancosController@index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/bancos/crear.blade.php
@extends('main')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading"><h2>Nuevo Banco</h2></div>
                <div class="panel-body">
                    {!! Form::open(array('route' => 'bancos.store','method'=>'POST', 'class'=>'form-horizontal')) !!}
                        <div class="form-group{{ $errors->has('codigo') ? ' has-error' : '' }}">
                            <label for="codigo" class="col-md-4 control-label">Sigla del Banco</label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="codigo" placeholder="SIGLA DEL BANCO" style="text-transform: uppercase">
                                @if ($errors->has('codigo'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('codigo') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('nombre') ? ' has-error' : '' }}">
                            <label for="nombre" class="col-md-4 control-label">Nombre del Banco</label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="nombre" placeholder="NOMBRE DEL BANCO" style="text-transform: uppercase">
                                @if ($errors->has('nombre'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('nombre') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('descripcion') ? ' has-error' : '' }}">
                            <div class="col-md-6 col-md-offset-4">
                                {!! Form::submit('Crear Banco', ['class' => 'btn btn-success']) !!}
                            </div>
                        </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/bancos/index.blade.php
@extends('main')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2>
                        Bancos
                        <div class="crear_empresa pull-right">
                            <a class="btn btn-success" href="{{ route('bancos.create') }}">Nuevo Banco</a>
                        </div>
                    </h2>
                    <div class="clearfix"></div>
                </div>

                <div class="panel-body">
                    <table class="table table-hover table-bordered">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Sigla</th>
                                <th>Nombre</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($bancos as $banco)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $banco->codigo }}</td>
                                <td>{{ $banco->nombre }}</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection